### ISSUE TITLE
Consider new name and update variables and functions

### ISSUE THREAD

**Issue by circAssimilate** [circAssimilate/Optimizely-Poll-For-Delayed-Content#1]
The current name is `pollForDelayedContent()`, which doesn't properly represent the DOM Mutation option. I recommend we change the name before publishing.

**Comment by tobiasurff** [comment]
@circAssimilate How about `observeSelector`, similar to http://developers.optimizely.com/javascript/personalization/index.html#observeSelector? This closely matches what will be available in p13n later on (and we might be able to feed back the DOM Mutation bit to product so they can include in p13n / A/B 2.0 clientjs in the future).

**Comment by circAssimilate** [comment]
Changed to waitForDelayedContent()
